lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: 'kafka.consumer<type=app-info, client-id=(.+)><>(.+): (.+)'
    name: kafka_consumer_app_info
    value: 1
    labels:
      client-id: $1
      $2: $3
    type: UNTYPED
  - pattern : 'kafka.consumer<type=(.+), client-id=(.+), node-id=(.+)><>(.+):'
    name: kafka_consumer_$1_$4
    type: GAUGE
    labels:
      client-id: $2
      node-id: $3
  - pattern : 'kafka.consumer<type=(.+), client-id=(.+), topic=(.+), partition=(.+)><>(.+):'
    name: kafka_consumer_$1_$5
    type: GAUGE
    labels:
      client-id: $2
      topic: $3
      partition: $4
  - pattern : 'kafka.consumer<type=(.+), client-id=(.+), topic=(.+)><>(.+):'
    name: kafka_consumer_$1_$4
    type: GAUGE
    labels:
      client-id: $2
      topic: $3
  - pattern : 'kafka.consumer<type=(.+), client-id=(.+)><>(.+):'
    name: kafka_consumer_$1_$3
    type: GAUGE
    labels:
      client-id: $2

  - pattern : 'kafka.producer<type=app-info, client-id=(.+)><>(.+): (.+)'
    name: kafka_producer_app_info
    value: 1
    labels:
      client-id: $1
      $2: $3
    type: UNTYPED
  - pattern : 'kafka.producer<type=(.+), client-id=(.+), node-id=(node-[0-9]+)><>(.+):'
    name: kafka_producer_$1_$4
    type: GAUGE
    labels:
      client-id: $2
      node-id: $3
  - pattern : 'kafka.producer<type=(.+), client-id=(.+), topic=([-\w]+)><>(.+):'
    name: kafka_producer_$1_$4
    type: GAUGE
    labels:
      client-id: $2
      topic: $3
  - pattern : 'kafka.producer<type=(.+), client-id=(.+)><>(.+):'
    name: kafka_producer_$1_$3
    type: GAUGE
    labels:
      client-id: $2

  - pattern : 'kafka.streams<type=stream-metrics, client-id=(.*)><>(.+): (.+)'
    name: kafka_streams_app_info
    value: 1
    labels:
      client-id: $1
      $2: $3
    type: UNTYPED
  - pattern : 'kafka.streams<type=(.+), thread-id=(.+), task-id=(.*), (.+)=(.+)><>(.+):'
    name: kafka_streams_$1_$6
    type: GAUGE
    labels:
      thread-id: $2
      task-id: $3
      $4: $5
  - pattern : 'kafka.streams<type=stream-task-metrics, thread-id=(.+), task-id=(.*)><>(.+):'
    name: kafka_streams_stream-task-metrics_$3
    type: GAUGE
    labels:
      thread-id: $1
      task-id: $2
  - pattern : 'kafka.streams<type=(.+), thread-id=(.+)><>(.+):'
    name: kafka_streams_$1_$3
    type: GAUGE
    labels:
      thread-id: $2
