global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'stream'
    scrape_interval: 10s
    static_configs:
      - targets: ['stream:7071']
  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
      - targets: ['kafka-1:7071', 'kafka-2:7071', 'kafka-3:7071']
  - job_name: 'zookeeper'
    scrape_interval: 10s
    static_configs:
      - targets: ['zk-1:7071', 'zk-2:7071', 'zk-3:7071']
  - job_name: 'tools'
    scrape_interval: 10s
    static_configs:
      - targets: ['tools:7071', 'tools:7072']
