{
 "title": "Kafka_stream_monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "client_id",
    "query": "label_values(kafka_streams_app_info, client_id)"
   },
   {
    "name": "thread_id",
    "query": "label_values(kafka_streams_stream_thread_metrics_commit_latency_avg, thread_id)"
   },
   {
    "name": "threadtask_id",
    "query": "label_values(kafka_streams_stream_task_metrics_record_lateness_avg, thread_id)"
   },
   {
    "name": "threadtasknode_id",
    "query": "label_values(kafka_streams_stream_processor_node_metrics_process_rate, thread_id)"
   },
   {
    "name": "threadtaskstate_id",
    "query": "label_values(kafka_streams_stream_state_metrics_put_latency_avg, thread_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics => KAFKA_STREAMS_APP_INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "version",
     "type": "singlestat",
     "description": "The version of the Kafka Streams client.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_streams_app_info{client_id=~\"$client_id\", version!=\"\"}"
      }
     ]
    },
    {
     "title": "commit_id",
     "type": "singlestat",
     "description": "The version control commit ID of the Kafka Streams client.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_streams_app_info{client_id=~\"$client_id\", commit_id!=\"\"}"
      }
     ]
    },
    {
     "title": "application_id",
     "type": "singlestat",
     "description": "The application ID of the Kafka Streams client.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_streams_app_info{client_id=~\"$client_id\", application_id!=\"\"}"
      }
     ]
    },
    {
     "title": "topology_description",
     "type": "singlestat",
     "description": "The description of the topology executed in the Kafka Streams client.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_streams_app_info{client_id=~\"$client_id\", topology_description!=\"\"}"
      }
     ]
    },
    {
     "title": "state",
     "type": "singlestat",
     "description": "The state of the Kafka Streams client.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_streams_app_info{client_id=~\"$client_id\", state!=\"\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_STREAMS_STREAM_THREAD_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "commit-latency-avg",
     "type": "graph",
     "description": "The average execution time in ms, for committing, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_avg{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "commit-latency-max",
     "type": "graph",
     "description": "The maximum execution time in ms, for committing, across all running tasks of this thread.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_latency_max{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "poll-latency-avg",
     "type": "graph",
     "description": "The average execution time in ms, for consumer polling.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_avg{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "poll-latency-max",
     "type": "graph",
     "description": "The maximum execution time in ms, for consumer polling.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_latency_max{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "process-latency-avg",
     "type": "graph",
     "description": "The average execution time in ms, for processing.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_avg{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "process-latency-max",
     "type": "graph",
     "description": "The maximum execution time in ms, for processing.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_latency_max{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "punctuate-latency-avg",
     "type": "graph",
     "description": "The average execution time in ms, for punctuating.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_avg{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "punctuate-latency-max",
     "type": "graph",
     "description": "The maximum execution time in ms, for punctuating.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_latency_max{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "commit-rate",
     "type": "graph",
     "description": "The average number of commits per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_rate{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "commit-total",
     "type": "graph",
     "description": "The total number of commit calls.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_commit_total{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "poll-rate",
     "type": "graph",
     "description": "The average number of consumer poll calls per second.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_rate{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "poll-total",
     "type": "graph",
     "description": "The total number of consumer poll calls.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_poll_total{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "process-rate",
     "type": "graph",
     "description": "The average number of processed records per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_rate{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "process-total",
     "type": "graph",
     "description": "The total number of processed records.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_process_total{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "punctuate-rate",
     "type": "graph",
     "description": "The average number of punctuate calls per second.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_rate{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "punctuate-total",
     "type": "graph",
     "description": "The total number of punctuate calls.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_punctuate_total{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "task-created-rate",
     "type": "graph",
     "description": "The average number of tasks created per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_task_created_rate{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "task-created-total",
     "type": "graph",
     "description": "The total number of tasks created.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_task_created_total{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "task-closed-rate",
     "type": "graph",
     "description": "The average number of tasks closed per second.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_task_closed_rate{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "task-closed-total",
     "type": "graph",
     "description": "The total number of tasks closed.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_thread_metrics_task_closed_total{thread_id=~\"$thread_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_STREAMS_STREAM_TASK_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "process-latency-avg",
     "type": "graph",
     "description": "The average execution time in ns, for processing.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_process_latency_avg{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "process-latency-max",
     "type": "graph",
     "description": "The maximum execution time in ns, for processing.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_process_latency_max{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "process-rate",
     "type": "graph",
     "description": "The average number of processed records per second across all source processor nodes of this task.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_process_rate{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "process-total",
     "type": "graph",
     "description": "The total number of processed records across all source processor nodes of this task.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_process_total{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "commit-latency-avg",
     "type": "graph",
     "description": "The average execution time in ns, for committing.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_commit_latency_avg{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "commit-latency-max",
     "type": "graph",
     "description": "The maximum execution time in ns, for committing.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_commit_latency_max{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "commit-rate",
     "type": "graph",
     "description": "The average number of commit calls per second.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_commit_rate{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "commit-total",
     "type": "graph",
     "description": "The total number of commit calls.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_commit_total{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "record-lateness-avg",
     "type": "graph",
     "description": "The average observed lateness of records (stream time - record timestamp).",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_record_lateness_avg{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "record-lateness-max",
     "type": "graph",
     "description": "The max observed lateness of records (stream time - record timestamp).",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_record_lateness_max{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "enforced-processing-rate",
     "type": "graph",
     "description": "The average number of enforced processings per second.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_enforced_processing_rate{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "enforced-processing-total",
     "type": "graph",
     "description": "The total number enforced processings.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_enforced_processing_total{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "dropped-records-rate",
     "type": "graph",
     "description": "The average number of records dropped within this task.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_dropped_records_rate{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "dropped-records-total",
     "type": "graph",
     "description": "The total number of records dropped within this task.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_task_metrics_dropped_records_total{thread_id=~\"$threadtask_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_STREAMS_STREAM_PROCESSOR_NODE_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "process-rate",
     "type": "graph",
     "description": "The average number of records processed by a source processor node per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_processor_node_metrics_process_rate{thread_id=~\"$threadtasknode_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "process-total",
     "type": "graph",
     "description": "The total number of records processed by a source processor node per second.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_processor_node_metrics_process_total{thread_id=~\"$threadtasknode_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "suppression-emit-rate",
     "type": "graph",
     "description": "The rate at which records that have been emitted downstream from suppression operation nodes.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_processor_node_metrics_suppression_emit_rate{thread_id=~\"$threadtasknode_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "suppression-emit-total",
     "type": "graph",
     "description": "The total number of records that have been emitted downstream from suppression operation nodes.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_processor_node_metrics_suppression_emit_total{thread_id=~\"$threadtasknode_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_STREAMS_STREAM_STATE_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "put-latency-avg",
     "type": "graph",
     "description": "The average put execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_latency_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "put-latency-max",
     "type": "graph",
     "description": "The maximum put execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_latency_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "put-if-absent-latency-avg",
     "type": "graph",
     "description": "The average put-if-absent execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "put-if-absent-latency-max",
     "type": "graph",
     "description": "The maximum put-if-absent execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_latency_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "get-latency-avg",
     "type": "graph",
     "description": "The average get execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_get_latency_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "get-latency-max",
     "type": "graph",
     "description": "The maximum get execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_get_latency_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "delete-latency-avg",
     "type": "graph",
     "description": "The average delete execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_latency_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "delete-latency-max",
     "type": "graph",
     "description": "The maximum delete execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_latency_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "put-all-latency-avg",
     "type": "graph",
     "description": "The average put-all execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_all_latency_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "put-all-latency-max",
     "type": "graph",
     "description": "The maximum put-all execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_all_latency_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "all-latency-avg",
     "type": "graph",
     "description": "The average all operation execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_all_latency_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "all-latency-max",
     "type": "graph",
     "description": "The maximum all operation execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_all_latency_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "range-latency-avg",
     "type": "graph",
     "description": "The average range execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_range_latency_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "range-latency-max",
     "type": "graph",
     "description": "The maximum range execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_range_latency_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "flush-latency-avg",
     "type": "graph",
     "description": "The average flush execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_flush_latency_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "flush-latency-max",
     "type": "graph",
     "description": "The maximum flush execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_flush_latency_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "restore-latency-avg",
     "type": "graph",
     "description": "The average restore execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_latency_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "restore-latency-max",
     "type": "graph",
     "description": "The maximum restore execution time in ns.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_latency_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "put-rate",
     "type": "graph",
     "description": "The average put rate for this store.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "put-if-absent-rate",
     "type": "graph",
     "description": "The average put-if-absent rate for this store.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_if_absent_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "get-rate",
     "type": "graph",
     "description": "The average get rate for this store.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_get_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "delete-rate",
     "type": "graph",
     "description": "The average delete rate for this store.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_delete_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "put-all-rate",
     "type": "graph",
     "description": "The average put-all rate for this store.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_put_all_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "all-rate",
     "type": "graph",
     "description": "The average all operation rate for this store.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_all_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "range-rate",
     "type": "graph",
     "description": "The average range rate for this store.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_range_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "flush-rate",
     "type": "graph",
     "description": "The average flush rate for this store.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_flush_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "restore-rate",
     "type": "graph",
     "description": "The average restore rate for this store.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_restore_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "suppression-buffer-size-avg",
     "type": "graph",
     "description": "The average total size, in bytes, of the buffered data over the sampling window.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_suppression_buffer_size_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "suppression-buffer-size-max",
     "type": "graph",
     "description": "The maximum total size, in bytes, of the buffered data over the sampling window.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_suppression_buffer_size_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "suppression-buffer-count-avg",
     "type": "graph",
     "description": "The average number of records buffered over the sampling window.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_suppression_buffer_count_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "suppression-buffer-count-max",
     "type": "graph",
     "description": "The maximum number of records buffered over the sampling window.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_suppression_buffer_count_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "bytes-written-rate",
     "type": "graph",
     "description": "The average number of bytes written per second to the RocksDB state store.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_written_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "bytes-written-total",
     "type": "graph",
     "description": "The total number of bytes written to the RocksDB state store.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_written_total{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "bytes-read-rate",
     "type": "graph",
     "description": "The average number of bytes read per second from the RocksDB state store.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_read_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "bytes-read-total",
     "type": "graph",
     "description": "The total number of bytes read from the RocksDB state store.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_read_total{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "memtable-bytes-flushed-rate",
     "type": "graph",
     "description": "The average number of bytes flushed per second from the memtable to disk.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_bytes_flushed_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "memtable-bytes-flushed-total",
     "type": "graph",
     "description": "The total number of bytes flushed from the memtable to disk.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_bytes_flushed_total{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "memtable-hit-ratio",
     "type": "graph",
     "description": "The ratio of memtable hits relative to all lookups to the memtable.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_memtable_hit_ratio{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "block-cache-data-hit-ratio",
     "type": "graph",
     "description": "The ratio of block cache hits for data blocks relative to all lookups for data blocks to the block cache.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_data_hit_ratio{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "block-cache-index-hit-ratio",
     "type": "graph",
     "description": "The ratio of block cache hits for index blocks relative to all lookups for index blocks to the block cache.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_index_hit_ratio{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "block-cache-filter-hit-ratio",
     "type": "graph",
     "description": "The ratio of block cache hits for filter blocks relative to all lookups for filter blocks to the block cache.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_block_cache_filter_hit_ratio{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "write-stall-duration-avg",
     "type": "graph",
     "description": "The average duration of write stalls in ms.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_write_stall_duration_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "write-stall-duration-total",
     "type": "graph",
     "description": "The total duration of write stalls in ms.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_write_stall_duration_total{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "bytes-read-compaction-rate",
     "type": "graph",
     "description": "The average number of bytes read per second during compaction.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_read_compaction_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "bytes-written-compaction-rate",
     "type": "graph",
     "description": "The average number of bytes written per second during compaction.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_bytes_written_compaction_rate{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "number-open-files",
     "type": "graph",
     "description": "The number of current open files.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_number_open_files{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "number-file-errors-total",
     "type": "graph",
     "description": "The total number of file errors occurred.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_state_metrics_number_file_errors_total{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_STREAMS_STREAM_RECORD_CACHE_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "hit-ratio-avg",
     "type": "graph",
     "description": "The average cache hit ratio defined as the ratio of cache read hits over the total cache read requests.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_record_cache_metrics_hit_ratio_avg{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "hit-ratio-min",
     "type": "graph",
     "description": "The mininum cache hit ratio.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_record_cache_metrics_hit_ratio_min{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    },
    {
     "title": "hit-ratio-max",
     "type": "graph",
     "description": "The maximum cache hit ratio.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_streams_stream_record_cache_metrics_hit_ratio_max{thread_id=~\"$threadtaskstate_id\"}",
       "legendFormat": "{{thread_id}} "
      }
     ]
    }
   ]
  }
 ]
}