{
 "title": "Kafka_producer_monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "client_id",
    "query": "label_values(kafka_producer_app_info, client_id)"
   },
   {
    "name": "clientnode_id",
    "query": "label_values(kafka_producer_producer_node_metrics_request_rate, client_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics => KAFKA_PRODUCER_APP_INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "version",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_producer_app_info{client_id=~\"$client_id\", version!=\"\"}"
      }
     ]
    },
    {
     "title": "commit_id",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_producer_app_info{client_id=~\"$client_id\", commit_id!=\"\"}"
      }
     ]
    },
    {
     "title": "start_time_ms",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_producer_app_info{client_id=~\"$client_id\", start_time_ms!=\"\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_PRODUCER_PRODUCER_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "connection-close-rate",
     "type": "graph",
     "description": "Connections closed per second in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_connection_close_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "connection-close-total",
     "type": "graph",
     "description": "Total connections closed in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_connection_close_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "connection-creation-rate",
     "type": "graph",
     "description": "New connections established per second in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_connection_creation_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "connection-creation-total",
     "type": "graph",
     "description": "Total new connections established in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_connection_creation_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "network-io-rate",
     "type": "graph",
     "description": "The average number of network operations (reads or writes) on all connections per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_network_io_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "network-io-total",
     "type": "graph",
     "description": "The total number of network operations (reads or writes) on all connections.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_network_io_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "outgoing-byte-rate",
     "type": "graph",
     "description": "The average number of outgoing bytes sent per second to all servers.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_outgoing_byte_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "outgoing-byte-total",
     "type": "graph",
     "description": "The total number of outgoing bytes sent to all servers.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_outgoing_byte_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-rate",
     "type": "graph",
     "description": "The average number of requests sent per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-total",
     "type": "graph",
     "description": "The total number of requests sent.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-size-avg",
     "type": "graph",
     "description": "The average size of all requests in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_size_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-size-max",
     "type": "graph",
     "description": "The maximum size of any request sent in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_size_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "incoming-byte-rate",
     "type": "graph",
     "description": "Bytes/second read off all sockets.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_incoming_byte_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "incoming-byte-total",
     "type": "graph",
     "description": "Total bytes read off all sockets.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_incoming_byte_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "response-rate",
     "type": "graph",
     "description": "Responses received per second.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_response_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "response-total",
     "type": "graph",
     "description": "Total responses received.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_response_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "select-rate",
     "type": "graph",
     "description": "Number of times the I/O layer checked for new I/O to perform per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_select_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "select-total",
     "type": "graph",
     "description": "Total number of times the I/O layer checked for new I/O to perform.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_select_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "io-wait-time-ns-avg",
     "type": "graph",
     "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_wait_time_ns_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "io-wait-ratio",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent waiting.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_wait_ratio{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "io-time-ns-avg",
     "type": "graph",
     "description": "The average length of time for I/O per select call in nanoseconds.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_time_ns_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "io-ratio",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent doing I/O.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_io_ratio{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "connection-count",
     "type": "graph",
     "description": "The current number of active connections.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_connection_count{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-authentication-rate",
     "type": "graph",
     "description": "Connections per second that were successfully authenticated using SASL or SSL.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_successful_authentication_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-authentication-total",
     "type": "graph",
     "description": "Total connections that were successfully authenticated using SASL or SSL.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_successful_authentication_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-authentication-rate",
     "type": "graph",
     "description": "Connections per second that failed authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_failed_authentication_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-authentication-total",
     "type": "graph",
     "description": "Total connections that failed authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_failed_authentication_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-reauthentication-rate",
     "type": "graph",
     "description": "Connections per second that were successfully re-authenticated using SASL.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_successful_reauthentication_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-reauthentication-total",
     "type": "graph",
     "description": "Total connections that were successfully re-authenticated using SASL.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_successful_reauthentication_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "reauthentication-latency-max",
     "type": "graph",
     "description": "The maximum latency in ms observed due to re-authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_reauthentication_latency_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "reauthentication-latency-avg",
     "type": "graph",
     "description": "The average latency in ms observed due to re-authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_reauthentication_latency_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-reauthentication-rate",
     "type": "graph",
     "description": "Connections per second that failed re-authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_failed_reauthentication_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-reauthentication-total",
     "type": "graph",
     "description": "Total connections that failed re-authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_failed_reauthentication_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-authentication-no-reauth-total",
     "type": "graph",
     "description": "Total connections that were successfully authenticated by older, pre-2.2.0 SASL clients that do not support re-authentication. May only be non-zero",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_successful_authentication_no_reauth_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_PRODUCER_PRODUCER_NODE_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "outgoing-byte-rate",
     "type": "graph",
     "description": "The average number of outgoing bytes sent per second for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_outgoing_byte_rate{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "outgoing-byte-total",
     "type": "graph",
     "description": "The total number of outgoing bytes sent for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_outgoing_byte_total{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-rate",
     "type": "graph",
     "description": "The average number of requests sent per second for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_request_rate{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-total",
     "type": "graph",
     "description": "The total number of requests sent for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_request_total{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-size-avg",
     "type": "graph",
     "description": "The average size of all requests in the window for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_request_size_avg{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-size-max",
     "type": "graph",
     "description": "The maximum size of any request sent in the window for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_request_size_max{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "incoming-byte-rate",
     "type": "graph",
     "description": "The average number of bytes received per second for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_incoming_byte_rate{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "incoming-byte-total",
     "type": "graph",
     "description": "The total number of bytes received for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_incoming_byte_total{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-latency-avg",
     "type": "graph",
     "description": "The average request latency in ms for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_request_latency_avg{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-latency-max",
     "type": "graph",
     "description": "The maximum request latency in ms for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_request_latency_max{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "response-rate",
     "type": "graph",
     "description": "Responses received per second for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_response_rate{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "response-total",
     "type": "graph",
     "description": "Total responses received for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_node_metrics_response_total{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_PRODUCER_PRODUCER_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "waiting-threads",
     "type": "graph",
     "description": "The number of user threads blocked waiting for buffer memory to enqueue their records.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_waiting_threads{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "buffer-total-bytes",
     "type": "graph",
     "description": "The maximum amount of buffer memory the client can use (whether or not it is currently used).",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_buffer_total_bytes{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "buffer-available-bytes",
     "type": "graph",
     "description": "The total amount of buffer memory that is not being used (either unallocated or in the free list).",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_buffer_available_bytes{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "bufferpool-wait-time",
     "type": "graph",
     "description": "The fraction of time an appender waits for space allocation.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_bufferpool_wait_time{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "batch-size-avg",
     "type": "graph",
     "description": "The average number of bytes sent per partition per-request.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_batch_size_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "batch-size-max",
     "type": "graph",
     "description": "The max number of bytes sent per partition per-request.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_batch_size_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "batch-split-rate",
     "type": "graph",
     "description": "The average number of batch splits per second",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_batch_split_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "batch-split-total",
     "type": "graph",
     "description": "The total number of batch splits",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_batch_split_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "compression-rate-avg",
     "type": "graph",
     "description": "The average compression rate of record batches.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_compression_rate_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "metadata-age",
     "type": "graph",
     "description": "The age in seconds of the current producer metadata being used.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_metadata_age{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "produce-throttle-time-avg",
     "type": "graph",
     "description": "The average time in ms a request was throttled by a broker",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_produce_throttle_time_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "produce-throttle-time-max",
     "type": "graph",
     "description": "The maximum time in ms a request was throttled by a broker",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_produce_throttle_time_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-error-rate",
     "type": "graph",
     "description": "The average per-second number of record sends that resulted in errors",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_error_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-error-total",
     "type": "graph",
     "description": "The total number of record sends that resulted in errors",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_error_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-queue-time-avg",
     "type": "graph",
     "description": "The average time in ms record batches spent in the send buffer.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_queue_time_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-queue-time-max",
     "type": "graph",
     "description": "The maximum time in ms record batches spent in the send buffer.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_queue_time_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-retry-rate",
     "type": "graph",
     "description": "The average per-second number of retried record sends",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_retry_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-retry-total",
     "type": "graph",
     "description": "The total number of retried record sends",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_retry_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-send-rate",
     "type": "graph",
     "description": "The average number of records sent per second.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_send_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-send-total",
     "type": "graph",
     "description": "The total number of records sent.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_send_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-size-avg",
     "type": "graph",
     "description": "The average record size",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_size_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-size-max",
     "type": "graph",
     "description": "The maximum record size",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_size_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-per-request-avg",
     "type": "graph",
     "description": "The average number of records per request.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_records_per_request_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-latency-avg",
     "type": "graph",
     "description": "The average request latency in ms",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_latency_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-latency-max",
     "type": "graph",
     "description": "The maximum request latency in ms",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_request_latency_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "requests-in-flight",
     "type": "graph",
     "description": "The current number of in-flight requests awaiting a response.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_requests_in_flight{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "byte-rate",
     "type": "graph",
     "description": "The average number of bytes sent per second for a topic.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_byte_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "byte-total",
     "type": "graph",
     "description": "The total number of bytes sent for a topic.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_byte_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "compression-rate",
     "type": "graph",
     "description": "The average compression rate of record batches for a topic.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_compression_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-error-rate",
     "type": "graph",
     "description": "The average per-second number of record sends that resulted in errors for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_error_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-error-total",
     "type": "graph",
     "description": "The total number of record sends that resulted in errors for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_error_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-retry-rate",
     "type": "graph",
     "description": "The average per-second number of retried record sends for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_retry_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-retry-total",
     "type": "graph",
     "description": "The total number of retried record sends for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_retry_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-send-rate",
     "type": "graph",
     "description": "The average number of records sent per second for a topic.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_send_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "record-send-total",
     "type": "graph",
     "description": "The total number of records sent for a topic.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_record_send_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    }
   ]
  }
 ]
}