{
 "title": "Kafka_consumer_monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "client_id",
    "query": "label_values(kafka_consumer_app_info, client_id)"
   },
   {
    "name": "clientnode_id",
    "query": "label_values(kafka_consumer_consumer_node_metrics_request_rate, client_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics => KAFKA_CONSUMER_APP_INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "version",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumer_app_info{client_id=~\"$client_id\", version!=\"\"}"
      }
     ]
    },
    {
     "title": "commit_id",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumer_app_info{client_id=~\"$client_id\", commit_id!=\"\"}"
      }
     ]
    },
    {
     "title": "start_time_ms",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_consumer_app_info{client_id=~\"$client_id\", start_time_ms!=\"\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_CONSUMER_CONSUMER_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "connection-close-rate",
     "type": "graph",
     "description": "Connections closed per second in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_connection_close_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "connection-close-total",
     "type": "graph",
     "description": "Total connections closed in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_connection_close_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "connection-creation-rate",
     "type": "graph",
     "description": "New connections established per second in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_connection_creation_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "connection-creation-total",
     "type": "graph",
     "description": "Total new connections established in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_connection_creation_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "network-io-rate",
     "type": "graph",
     "description": "The average number of network operations (reads or writes) on all connections per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_network_io_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "network-io-total",
     "type": "graph",
     "description": "The total number of network operations (reads or writes) on all connections.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_network_io_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "outgoing-byte-rate",
     "type": "graph",
     "description": "The average number of outgoing bytes sent per second to all servers.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_outgoing_byte_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "outgoing-byte-total",
     "type": "graph",
     "description": "The total number of outgoing bytes sent to all servers.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_outgoing_byte_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-rate",
     "type": "graph",
     "description": "The average number of requests sent per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_request_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-total",
     "type": "graph",
     "description": "The total number of requests sent.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_request_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-size-avg",
     "type": "graph",
     "description": "The average size of all requests in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_request_size_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-size-max",
     "type": "graph",
     "description": "The maximum size of any request sent in the window.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_request_size_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "incoming-byte-rate",
     "type": "graph",
     "description": "Bytes/second read off all sockets.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_incoming_byte_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "incoming-byte-total",
     "type": "graph",
     "description": "Total bytes read off all sockets.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_incoming_byte_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "response-rate",
     "type": "graph",
     "description": "Responses received per second.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_response_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "response-total",
     "type": "graph",
     "description": "Total responses received.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_response_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "select-rate",
     "type": "graph",
     "description": "Number of times the I/O layer checked for new I/O to perform per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_select_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "select-total",
     "type": "graph",
     "description": "Total number of times the I/O layer checked for new I/O to perform.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_select_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "io-wait-time-ns-avg",
     "type": "graph",
     "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_io_wait_time_ns_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "io-wait-ratio",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent waiting.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_io_wait_ratio{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "io-time-ns-avg",
     "type": "graph",
     "description": "The average length of time for I/O per select call in nanoseconds.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_io_time_ns_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "io-ratio",
     "type": "graph",
     "description": "The fraction of time the I/O thread spent doing I/O.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_io_ratio{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "connection-count",
     "type": "graph",
     "description": "The current number of active connections.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_connection_count{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-authentication-rate",
     "type": "graph",
     "description": "Connections per second that were successfully authenticated using SASL or SSL.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_successful_authentication_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-authentication-total",
     "type": "graph",
     "description": "Total connections that were successfully authenticated using SASL or SSL.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_successful_authentication_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-authentication-rate",
     "type": "graph",
     "description": "Connections per second that failed authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_failed_authentication_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-authentication-total",
     "type": "graph",
     "description": "Total connections that failed authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_failed_authentication_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-reauthentication-rate",
     "type": "graph",
     "description": "Connections per second that were successfully re-authenticated using SASL.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_successful_reauthentication_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-reauthentication-total",
     "type": "graph",
     "description": "Total connections that were successfully re-authenticated using SASL.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_successful_reauthentication_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "reauthentication-latency-max",
     "type": "graph",
     "description": "The maximum latency in ms observed due to re-authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_reauthentication_latency_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "reauthentication-latency-avg",
     "type": "graph",
     "description": "The average latency in ms observed due to re-authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_reauthentication_latency_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-reauthentication-rate",
     "type": "graph",
     "description": "Connections per second that failed re-authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_failed_reauthentication_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-reauthentication-total",
     "type": "graph",
     "description": "Total connections that failed re-authentication.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_failed_reauthentication_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "successful-authentication-no-reauth-total",
     "type": "graph",
     "description": "Total connections that were successfully authenticated by older, pre-2.2.0 SASL clients that do not support re-authentication. May only be non-zero",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_successful_authentication_no_reauth_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_CONSUMER_CONSUMER_NODE_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "outgoing-byte-rate",
     "type": "graph",
     "description": "The average number of outgoing bytes sent per second for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_outgoing_byte_rate{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "outgoing-byte-total",
     "type": "graph",
     "description": "The total number of outgoing bytes sent for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_outgoing_byte_total{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-rate",
     "type": "graph",
     "description": "The average number of requests sent per second for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_request_rate{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-total",
     "type": "graph",
     "description": "The total number of requests sent for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_request_total{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-size-avg",
     "type": "graph",
     "description": "The average size of all requests in the window for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_request_size_avg{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-size-max",
     "type": "graph",
     "description": "The maximum size of any request sent in the window for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_request_size_max{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "incoming-byte-rate",
     "type": "graph",
     "description": "The average number of bytes received per second for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_incoming_byte_rate{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "incoming-byte-total",
     "type": "graph",
     "description": "The total number of bytes received for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_incoming_byte_total{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-latency-avg",
     "type": "graph",
     "description": "The average request latency in ms for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_request_latency_avg{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "request-latency-max",
     "type": "graph",
     "description": "The maximum request latency in ms for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_request_latency_max{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "response-rate",
     "type": "graph",
     "description": "Responses received per second for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_response_rate{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "response-total",
     "type": "graph",
     "description": "Total responses received for a node.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_node_metrics_response_total{client_id=~\"$clientnode_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_CONSUMER_CONSUMER_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "time-between-poll-avg",
     "type": "graph",
     "description": "The average delay between invocations of poll().",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_time_between_poll_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "time-between-poll-max",
     "type": "graph",
     "description": "The max delay between invocations of poll().",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_time_between_poll_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "last-poll-seconds-ago",
     "type": "graph",
     "description": "The number of seconds since the last poll() invocation.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_last_poll_seconds_ago{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "poll-idle-ratio-avg",
     "type": "graph",
     "description": "The average fraction of time the consumer's poll() is idle as opposed to waiting for the user code to process records.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_metrics_poll_idle_ratio_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_CONSUMER_CONSUMER_COORDINATOR_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "commit-latency-avg",
     "type": "graph",
     "description": "The average time taken for a commit request",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_commit_latency_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "commit-latency-max",
     "type": "graph",
     "description": "The max time taken for a commit request",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_commit_latency_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "commit-rate",
     "type": "graph",
     "description": "The number of commit calls per second",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "commit-total",
     "type": "graph",
     "description": "The total number of commit calls",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_commit_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "assigned-partitions",
     "type": "graph",
     "description": "The number of partitions currently assigned to this consumer",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_assigned_partitions{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "heartbeat-response-time-max",
     "type": "graph",
     "description": "The max time taken to receive a response to a heartbeat request",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_heartbeat_response_time_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "heartbeat-rate",
     "type": "graph",
     "description": "The average number of heartbeats per second",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_heartbeat_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "heartbeat-total",
     "type": "graph",
     "description": "The total number of heartbeats",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_heartbeat_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "join-time-avg",
     "type": "graph",
     "description": "The average time taken for a group rejoin",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_join_time_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "join-time-max",
     "type": "graph",
     "description": "The max time taken for a group rejoin",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_join_time_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "join-rate",
     "type": "graph",
     "description": "The number of group joins per second",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_join_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "join-total",
     "type": "graph",
     "description": "The total number of group joins",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_join_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "sync-time-avg",
     "type": "graph",
     "description": "The average time taken for a group sync",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_sync_time_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "sync-time-max",
     "type": "graph",
     "description": "The max time taken for a group sync",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_sync_time_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "sync-rate",
     "type": "graph",
     "description": "The number of group syncs per second",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_sync_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "sync-total",
     "type": "graph",
     "description": "The total number of group syncs",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_sync_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "rebalance-latency-avg",
     "type": "graph",
     "description": "The average time taken for a group rebalance",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_latency_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "rebalance-latency-max",
     "type": "graph",
     "description": "The max time taken for a group rebalance",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_latency_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "rebalance-latency-total",
     "type": "graph",
     "description": "The total time taken for group rebalances so far",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_latency_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "rebalance-total",
     "type": "graph",
     "description": "The total number of group rebalances participated",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "rebalance-rate-per-hour",
     "type": "graph",
     "description": "The number of group rebalance participated per hour",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_rate_per_hour{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-rebalance-total",
     "type": "graph",
     "description": "The total number of failed group rebalances",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_failed_rebalance_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "failed-rebalance-rate-per-hour",
     "type": "graph",
     "description": "The number of failed group rebalance event per hour",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_failed_rebalance_rate_per_hour{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "last-rebalance-seconds-ago",
     "type": "graph",
     "description": "The number of seconds since the last rebalance event",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_last_rebalance_seconds_ago{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "last-heartbeat-seconds-ago",
     "type": "graph",
     "description": "The number of seconds since the last controller heartbeat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_last_heartbeat_seconds_ago{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "partitions-revoked-latency-avg",
     "type": "graph",
     "description": "The average time taken by the on-partitions-revoked rebalance listener callback",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_partitions_revoked_latency_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "partitions-revoked-latency-max",
     "type": "graph",
     "description": "The max time taken by the on-partitions-revoked rebalance listener callback",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_partitions_revoked_latency_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "partitions-assigned-latency-avg",
     "type": "graph",
     "description": "The average time taken by the on-partitions-assigned rebalance listener callback",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_partitions_assigned_latency_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "partitions-assigned-latency-max",
     "type": "graph",
     "description": "The max time taken by the on-partitions-assigned rebalance listener callback",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_partitions_assigned_latency_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "partitions-lost-latency-avg",
     "type": "graph",
     "description": "The average time taken by the on-partitions-lost rebalance listener callback",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_partitions_lost_latency_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "partitions-lost-latency-max",
     "type": "graph",
     "description": "The max time taken by the on-partitions-lost rebalance listener callback",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_coordinator_metrics_partitions_lost_latency_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics => KAFKA_CONSUMER_CONSUMER_FETCH_MANAGER_METRICS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "bytes-consumed-rate",
     "type": "graph",
     "description": "The average number of bytes consumed per second",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "bytes-consumed-total",
     "type": "graph",
     "description": "The total number of bytes consumed",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-latency-avg",
     "type": "graph",
     "description": "The average time taken for a fetch request.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-latency-max",
     "type": "graph",
     "description": "The max time taken for any fetch request.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-rate",
     "type": "graph",
     "description": "The number of fetch requests per second.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-size-avg",
     "type": "graph",
     "description": "The average number of bytes fetched per request",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-size-max",
     "type": "graph",
     "description": "The maximum number of bytes fetched per request",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-throttle-time-avg",
     "type": "graph",
     "description": "The average throttle time in ms",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-throttle-time-max",
     "type": "graph",
     "description": "The maximum throttle time in ms",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-total",
     "type": "graph",
     "description": "The total number of fetch requests.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-consumed-rate",
     "type": "graph",
     "description": "The average number of records consumed per second",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-consumed-total",
     "type": "graph",
     "description": "The total number of records consumed",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-lag-max",
     "type": "graph",
     "description": "The maximum lag in terms of number of records for any partition in this window",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-lead-min",
     "type": "graph",
     "description": "The minimum lead in terms of number of records for any partition in this window",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lead_min{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-per-request-avg",
     "type": "graph",
     "description": "The average number of records in each request",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_per_request_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "bytes-consumed-rate",
     "type": "graph",
     "description": "The average number of bytes consumed per second for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "bytes-consumed-total",
     "type": "graph",
     "description": "The total number of bytes consumed for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-size-avg",
     "type": "graph",
     "description": "The average number of bytes fetched per request for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "fetch-size-max",
     "type": "graph",
     "description": "The maximum number of bytes fetched per request for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_size_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-consumed-rate",
     "type": "graph",
     "description": "The average number of records consumed per second for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-consumed-total",
     "type": "graph",
     "description": "The total number of records consumed for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-per-request-avg",
     "type": "graph",
     "description": "The average number of records in each request for a topic",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_per_request_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "preferred-read-replica",
     "type": "graph",
     "description": "The current read replica for the partition, or -1 if reading from leader",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_preferred_read_replica{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-lag",
     "type": "graph",
     "description": "The latest lag of the partition",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-lag-avg",
     "type": "graph",
     "description": "The average lag of the partition",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-lag-max",
     "type": "graph",
     "description": "The max lag of the partition",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag_max{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-lead",
     "type": "graph",
     "description": "The latest lead of the partition",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lead{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-lead-avg",
     "type": "graph",
     "description": "The average lead of the partition",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lead_avg{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    },
    {
     "title": "records-lead-min",
     "type": "graph",
     "description": "The min lead of the partition",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lead_min{client_id=~\"$client_id\"}",
       "legendFormat": "{{client_id}} "
      }
     ]
    }
   ]
  }
 ]
}